### ISSUE TITLE
Uncaught TypeError: Cannot read property 'injection' of undefined 

### ISSUE THREAD

**Issue by beingfranklin** [smhatre59/cloudstorage#3]
We cannot use react-tap-event-plugin after React 16.4.0
https://github.com/zilverline/react-tap-event-plugin/issues/121
<img width="786" alt="Screenshot 2019-04-16 at 3 16 36 PM" src="https://user-images.githubusercontent.com/2555503/56199542-bc100380-605a-11e9-9473-e99283d4a08e.png">

**Comment by velykov** [comment]
I have a same error on react v16.3.0

**Comment by unnatim** [comment]
Same issue on react v16.8.6

**Comment by smhatre59** [comment]
@unnatim  I removed the npm dependency for now as a quick fix. Will rewrite the entire frontend codebase with updated material ui npm when I get time.

**Comment by unnatim** [comment]
@smhatre59 Thank you for replying smhatre59. I am a beginner in this React JS language. Please explain what do you mean by removing the npm dependency.

**Comment by smhatre59** [comment]
@unnatim There was a node module which was causing the app to crash due to incompatibility with recent react.js version. I have removed the node module from package.json file and the related code from the project. Kindly redownload the project and run it. I will take up the process of changing the entire codebase to recent material UI versions soon. Till then this is a minor bug fix which will keep the project in working condition.
